### ISSUE TITLE
First deadline: next Tuesday

### ISSUE THREAD

**Issue by patceline** [patceline/wikileaks-data-analytics#2]
Hey all, as said before, we need to get moving with our project. 

The first thing we need to do is to get everything set up. 

We need to get the data, create a database and start looking at algorithms that we can use. If you are good at one of these things, let me know. I will assign tasks to people tomorrow if I haven't heard back from you (except those who already contacted me)

**Comment by fbriant** [comment]
You said "create a database", will we use the course cluster ?

I'm not particulary expert at any of these, but as I said you can assign me any task ;-)

**Comment by fouweric** [comment]
@fbriant The course cluster is the only solution, or =)) ?

**Comment by fbriant** [comment]
@fouweric I supposed so,  at least I think it is the simplest one ;-)

**Comment by HKassir72** [comment]
Yes we can upload the data to the HDFS cluster, but then we can process it with Hadoop, Spark, or other software tools.
