### ISSUE TITLE
WP1 - PlusD: Data Crawling

### ISSUE THREAD

**Issue by agulfy** [patceline/wikileaks-data-analytics#4]
We need a group of 2 or 3 to do some data crawling.

Your task will be to find valid page_ids for diplomatic cables on the wikileaks page. Each diplomatic cable has a reference id in the form of 1973STATE097844_b , you can easily tweak URLs to access the data: http://search.wikileaks.org/plusd/cables/1973STATE097844_b.html

However, in order to gather all the valid page ids, we have to go the search pages and get the ids from there. You can search the public library here: https://www.wikileaks.org/plusd/?q=&qtfrom=1966-01-01&qtto=2010-12-31#result Note the qtfrom and qtto parameters at the url. By modifying these parameters you can get all the page_ids of cables of certain date.

Final expected result: After you get the valid ids, you should just fetch the pages and save it into the group directory in the cluster.

**Comment by fouweric** [comment]
Have an idea about this one:
- Create a script to split the interval 1973 - 2010 into XX date-chunks (e.g. yearly for instance: (1973, 1974), (1974, 1975), (1975, 1976), ..., (2009, 2010)) and save each chunk one line of a file "input_dates.txt" ( e.g. date-chunk_1 \n date-chunk_2 \n etc.. )
- "input_dates.txt" is InputFileFormat to a mapreduce task
- the mapper outputs the pairs (..., page_id) for each page_id of documents found in the interval of the date chunk
- the reducer save the html file corresponding to its pair.page_id

This way, we can parallelize the fetch of the 2M documents :santa: 

@fbriant @agulfy What do you think?

**Comment by fbriant** [comment]
Should I work on this task too ? I thought it would be an other group of people in order to be faster.
But that's no problem for me, I would gladly work on this too.

For your date-chunks

`(1973,1974)`
`(1974,1975)`

you mean the intervals

`from 1st January 1973 to 31st December 1973`
`from 1st Januray 1974 to 31st December 1974`

 right ?

> the reducer save the html file corresponding to its pair.page_id

So the reducer get itself the HTML page and save it in the cluster ?
I would to say to let each mapper get the HTML files for a date-chunk (as it gets the date-chunk from the RecordReader) and save them in the cluster and to have no particular reduce step.
Or is that what you meant ?

**Comment by fouweric** [comment]
Haha =P
That's perfectly right. No need to have a reducer, but for the modularization aspect of it.
Ty for your comment! (actually don't need help, but I will cry for it in case I get stuck on the task =p )
cheers,

**Comment by HKassir72** [comment]
Guys, you mentioned earlier something about downloading the data directly as SQL, what happened with that idea?

**Comment by fouweric** [comment]
@HKassir72 The SQL archive?
That was only a subset of the plusD data (the cablegate data)
And the SQL dump does not contain as many informations as the website =))

But its a fallback in case of failure. Have a look at what we discussed in issue #3

**Comment by fouweric** [comment]
Ahh, just found a way way way more simple solution for this issue.. (without using the dates)
It should be implemented by tonight.

**Comment by fouweric** [comment]
Arg, there is a bug on the EPFL cluster with the code.
Investigating..

**Comment by fouweric** [comment]
It has something to do with HDFS (with a local fs, it works perfectly)
Just asked on the forum: http://moodle.epfl.ch/mod/forum/discuss.php?d=196127

**Comment by fouweric** [comment]
Ok, the bug was only that epfl-workers are not connected to www :laughing: 

There are some stats! They were computed on the first 1k documents crawled ran on my machine between 21:07:04 and 21:21:01 => **it took 14min~ to crawl 1k documents on 1 machine.**
- # of documents = 2,325,960
- Each of average size = 55 KB
- in a .gz archive (the actual output of the crawler) = 14 KB
- reduction ratio = 55/14 = 4x
- Total size of data to download = 2,325,960 * 55 KB = **122 GB**
- Time for a single machine to crawl 1k documents = 14min*60 = 840 seconds

- The entire crawling should take...
- with 1 worker: 22.6 days
- with 2 workers: 11.3 days
- **with 4 workers: 5.6 days**
- **with 8 workers: 2.3 days**
- with 16 workers: 34 hours
- with 32 workers: 17 hours
- with 64 workers: 8.5 hours

I am waiting for the windows azure passes that the professor might give us.

**Comment by agulfy** [comment]
I am reopening this if you don't mind. (and I would rather close it when our initial goal-the directory in the cluster- is reached. So others can be aware of who is responsible for what)

We could assign a group member to deal with tokens, setup hadoop and application on azure, supervising the tasks and moving the directories to the cluster etc, unless you want to take care of everything. Then we can have someone else for parsing the html output?

**Comment by fbriant** [comment]
I will take care of parsing the html output ASAP if that's okay for you ;-)
(sorry for my inactivity these last days)

**Comment by agulfy** [comment]
@xPh3n0m 

Take a look at this issue and especially my last comment before this. You can find the relevant code on the repo. You *MUST* start running the program by Sunday 22 April. If there is any delay, almost all other tasks will be delayed further. Considering we are already behind the schedule, we can't really have that. Let me or @fouweric  know if you run into any problems.

**Comment by ElSeidy** [comment]
+1

**Comment by fouweric** [comment]
(redirections from the http protocol to https appeared today, making the crawler KO, fixed this unexpected case in the previous commit cee46bc9bdd4208e60bc19851b849693073c5bad)

@xPh3n0m [Here is the crawler as a .jar file.](https://drive.google.com/file/d/0B1F7dUzXsi1wOTdUTGd1MlhXaG8/view?usp=sharing)

Use case: crawl first 100k documents

    hadoop jar cables-crawler.jar app.Crawler 1 100000 &> hadoop-log.txt &

And to follow progress

    tail -f hadoop-log.txt

Number of docs crawled

    ls -l pages-crawled/ | wc -l

**Comment by xPh3n0m** [comment]
Ok I will try starting the crawl later today. I'll let you know about the status and if I find any issues

**Comment by xPh3n0m** [comment]
@fouweric I have some issues with the above. I have tried to crawl a small number of pages, but I get no results in the "pages-crawled" folder.

Is the issue discussed here still active: http://moodle.epfl.ch/mod/forum/discuss.php?d=196127

Let me know if I missed something

**Comment by agulfy** [comment]
Are you trying to run it in the cluster?

**Comment by xPh3n0m** [comment]
Yes indeed

**Comment by agulfy** [comment]
Then, it is probably the same issue. We need to do it on another machine. Can you discuss this with the TA to receive instructions on setting up the machine that will do this process.

**Comment by fouweric** [comment]
@xPh3n0m No, You did perfectly well =)
That's simply because there is no internet connection on epfl cluster :disappointed:

**Comment by xPh3n0m** [comment]
Ok I asked Mohammed and received this reply from Pr. Koch:


Mohammed, I thought you had talked to the team about this?

Thierry, find a partial mirror of www.wikileaks.org on hdfs:///datasets/www.wikileaks.org.tar
Currently, this contains 320k files. This will get automatically updated with time.

We have requested the Azure passes but have not received them yet.

Mohammed, please talk to the team about the many small files issue and HDFS.

c


Have you guys already received this info somehow?

**Comment by xPh3n0m** [comment]
FYI: Mohammed's reply:

We have some crawled HTML pages on the cluster. you find them on the path Christoph mentioned. Most importantly, these are tooo many small files. HDFS is not suitable for that, and this it needs some cleaning, something like merging many of these HTML files in larges ones, to make it easier to operate with.

I dont think the Azure machines is a good idea, it will require a lot of setting up and u will waste a lot of time for that.

-----

Were you already addressing the issue in the crawl code? Can we adapt it using the mentioned pages that are on the cluster?

**Comment by fouweric** [comment]
Multiple instance of the jar can be run on a machine. The setup required is a single node setup. 

Mirror of prof Koch is super set of plusD documents. 

Jar outputs HTML or gz. No adaptation inside the Java code possible. Shell script or other can do the job

**Comment by fouweric** [comment]
Found less than 50k cables of the total 2.3M cables on the epfl-mirror.
Perhaps that's because the cables are accessed via a .php form (?)

I am actually running 100 instances of an adaptation of the initial hadoop crawler. It is a simple java jar version of the hadoop mapreduce.

I began this morning at 10am with 2 initial computers and 20 instances of the crawler running on each.
**There is actually 317K documents (4GB~) crawled by these 2 computers.** (on my local disk)

I just launched 3 other computers and 60 instances.
In total, there is actually 100 instances running on a total of 5 computers.

**The actual speed is: 1665 documents / minute**

Will soon begin to upload the docs to our project folder on the epfl cluster. (not in hdfs, because each file is ~55K)

@xPh3n0m Can you do a script to group the html pages into bigger files?

**Comment by xPh3n0m** [comment]
Ok I'll try tomorrow

**Comment by fouweric** [comment]
Cool! Ty!
Update: 690K docs crawled (9GB of .gz)

**Comment by ElSeidy** [comment]
:+1:

**Comment by fouweric** [comment]
Update: 1,426K docs crawled (19GB of .gz), current speed: 1010 docs/minute

**Comment by agulfy** [comment]
>  Have you guys already received this info somehow?

No, at least not me.

> @xPh3n0m Can you do a script to group the html pages(compressed in gz files) into bigger files?

Can you let me and @fbriant know when the script is ready or how the files will be merged? Depending on the resulting (larger) files, the program for #5 must be modified a little.

**Comment by fbriant** [comment]
Indeed I will need to modify some stuff !

**Comment by fouweric** [comment]
What about the following file format :
<<<
N = #of HTML pages in the file 
PageID of page 1/N
PageID of page 2/N
PageID of page 3/N
...
PageID of page N/N
Page 1 content 
Page 2 content 
Page 3 content 
... 
Page N content 
EOF>>>

Each file contains hence 2*N+1 lines

**Comment by xPh3n0m** [comment]
Ok I will follow the above convention for the script, you can then already adapt your code.

Also, do we have an idea of what is considered as a "small" file?

**Comment by fbriant** [comment]
Indeed, this format make things easier for the record reader ;-)

**Comment by xPh3n0m** [comment]
@fouweric can you upload a subset of the html files that you crawled in order to test the script? Thx

**Comment by fouweric** [comment]
How big should it be?

**Comment by xPh3n0m** [comment]
Not that big, enough to create a few larger html files, depending on how large big files should be

Are the files organized in folders?

**Comment by fouweric** [comment]
Can you use the jar in this zip? 
https://docs.google.com/file/d/0B1F7dUzXsi1wcWFZakhRdjhRSjg/edit?usp=docslist_api

You can launch it with 2 arguments: from and to. 
It's the jar of the crawler which downloads (to - from) documents.

**Comment by xPh3n0m** [comment]
Ok I added the script on github: https://github.com/patceline/wikileaks-data-analytics/blob/master/groups/plusd/merge_small_files.bash

It uses two arguments: 
1. The number of small files to be treated
2.  The approximative size of the larger files

The script will therefore create larger files of about the approx size, and stop when all files are treated or when the first argument is reached.

It will save the larger files in "files_merged" and it will move the small html.gz files already treated in "files_merged/saved".

I used the following convention for the larger files:
<nb_documents> N </nb_documents>
<document_id id=DOCNAME1 />
<document_id id=DOCNAME2 />
<document_id id=DOCNAME3 />
...
<document_id id=DOCNAMEN />

<document_content id=DOCNAME1>
content of doc 1
</document_content>
<document_content id=DOCNAME2>
content of doc 2
</document_content>
.....



Let me know if the above is fine with you guys, I can do modifications if needed

**Comment by fouweric** [comment]
@xPh3n0m Nice:

Update: All documents crawled. Transferring them to icportal2 (will then send a tar of the docs in our team folder in hdfs)

**Comment by fouweric** [comment]
:+1: 2,014,07**5** documents are now in hdfs:///projects/wikileaks/plusd-raw-crawl.tar (26.7GB of .gz archives)

(Wikileaks says that there are 2.3M docs, in fact, there are 2.3M indexes pointing to a set of 2,014,07**8** documents. Yes, the are three documents indexed but unreachable 1977BOMBAY03008_c, 1977STATE275286_c, 1977TOKYO04712_c)

**Comment by fouweric** [comment]
@xPh3n0m Can you run your script on the tar?

**Comment by xPh3n0m** [comment]
I am doing it right now. About 600,000 html files merged into larger html files of about 100MB, and available on hdfs:///projects/wikileaks/plusd/

**Comment by xPh3n0m** [comment]
FYI all the html files are available on hdfs:///projects/wikileaks/plusd/

**Comment by fouweric** [comment]
Super, ty!
@agulfy @fbriant Your turn to bring the data to the DB!
